export const countryCodes = [
    { code: 'TH', name: 'Thailand', dial_code: '+66' },
    { code: 'US', name: 'United States', dial_code: '+1' },
    { code: 'GB', name: 'United Kingdom', dial_code: '+44' },
    { code: 'JP', name: 'Japan', dial_code: '+81' },
    { code: 'KR', name: 'South Korea', dial_code: '+82' },
    { code: 'CN', name: 'China', dial_code: '+86' },
    { code: 'SG', name: 'Singapore', dial_code: '+65' },
    { code: 'MY', name: 'Malaysia', dial_code: '+60' },
    { code: 'VN', name: 'Vietnam', dial_code: '+84' },
    { code: 'LA', name: 'Laos', dial_code: '+856' },
    { code: 'MM', name: 'Myanmar', dial_code: '+95' },
    { code: 'KH', name: 'Cambodia', dial_code: '+855' },
    { code: 'ID', name: 'Indonesia', dial_code: '+62' },
    { code: 'PH', name: 'Philippines', dial_code: '+63' },
    { code: 'IN', name: 'India', dial_code: '+91' },
    { code: 'AU', name: 'Australia', dial_code: '+61' },
    { code: 'NZ', name: 'New Zealand', dial_code: '+64' },
    { code: 'FR', name: 'France', dial_code: '+33' },
    { code: 'DE', name: 'Germany', dial_code: '+49' },
    { code: 'IT', name: 'Italy', dial_code: '+39' },
    { code: 'RU', name: 'Russia', dial_code: '+7' },
    { code: 'AE', name: 'United Arab Emirates', dial_code: '+971' },
    // Add more as needed, covering major tourism sources for Thailand context
];
